server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: application/json,application/problem+json
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: devprep-api
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${